### ISSUE TITLE
Disable VNET selection based on address range when deploying FortGate

### ISSUE THREAD

**Issue by suwonbuffalo** [fortinet/azure-templates#19]
Hi.
I was trying to install FortiGate at Azure marketplace and found something strange.

If the VNET address space is prefix25-32, VNET selection is disabled.
And prefix28-32 doesn't appear on the selection list either.
Please refer to the picture.
![image](https://user-images.githubusercontent.com/86699155/123895615-10350300-d99b-11eb-9d8a-66a82cd5a6c6.png)
![image](https://user-images.githubusercontent.com/86699155/123895650-1e831f00-d99b-11eb-9767-9e9417935446.png)

I want to use VNET address range as prefix26.

Please let me know why VNET selection is disabled.
Also, I wonder if it is Azure or Fortinet restrictions.

I look forward to hearing from you.
Have a nice day

**Comment by jvhoof** [comment]
Hi,

Thank you for contacting Fortinet. We have reviewed your report and it seems the minimum values are a little too strict. We will be working on getting these changed. For now, can you try with the templates on the GitHub repo below which already have the changes applied. Select the deployment you would like and use the 'Deploy to Azure' button next to the Azure Portal Wizard text.

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate

Hope this helps you in your deployment.

Kind regards,

Joeri

**Comment by suwonbuffalo** [comment]
Hi, Joeri

Thank you for your quick reply.

I deployed Fortgate using the modified template.
The creation of a new VNET seems to remove the address space (prefix25 to 32).
However, previously created VNETs are still not available.
![image](https://user-images.githubusercontent.com/86699155/124055900-b64a4100-da5f-11eb-8e2a-a2594a8aff6c.png)

I look forward to hearing from you about this.
Have a nice day :)

**Comment by jvhoof** [comment]
Hi,

One limitation I hadn't removed was the size of the subnet. It has now been lowered to the smalest size possible for the deployment. Can you retry again in the below repo?

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate

Regards,

Joeri

**Comment by suwonbuffalo** [comment]
Hello, Mr.Jorrie.

Thank you for applying the revised VNET form

Thank you.

**Comment by jvhoof** [comment]
Closing the issue now. We will publish this on the repo here as well this week.
