### ISSUE TITLE
'Microsoft.Template' is not valid

### ISSUE THREAD

**Issue by hameedjafar** [fortinet/azure-templates#2]
Hi All,

I faced the below Error-01, seems to be VM (Standard_F4) Unavailability in US North Central. Then, i checked the availability of DS3_v2 and tried to change the Instance Type to "DS3_v2" and "Standard_DS3_v2" and i got the error (Error-02) pasted at the last section of this page. 

Kindly assist, if possible..

Error-01:
---------
{"telemetryId":"5a7caecf-ff2e-4a59-b4c7-cca981674c70","bladeInstanceId":"Blade_50ef9c8683b64730985998e7c95db548_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"MultipleErrorsOccurred","message":"Multiple error occurred: BadRequest,BadRequest. Please see details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod_01-A' failed validation with message: 'The requested size for resource '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod_01-A' is currently not available in location 'North Central US' zones '' for subscription 'efbc14f0-5afe-4e56-92db-6b2fe58a43a4'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."},{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod_01-B' failed validation with message: 'The requested size for resource '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod_01-B' is currently not available in location 'North Central US' zones '' for subscription 'efbc14f0-5afe-4e56-92db-6b2fe58a43a4'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."}]}

------------------------------------
Error-02:
---------
Deployment validation failed.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '29f7560a-2973-419c-9525-1687acfaa56a'. See inner errors for details.

---------------------------------

**Comment by hameedjafar** [comment]
Also, kindly could someone suggest on what is the accurate value to change the Instance type to DS3_v2. This template has "Standard_F4".
I tried "DS3_v2" and "Standard_DS3_v2".. Seems to be not working..

**Comment by jvhoof** [comment]
Hi,
"Standard_DS3_v2" should be the correct naming. Which template are you trying to deploy and causes this issue. You can try my template for each of the deployment which lists the Standard_DS3_v2 SKU in the template here: https://github.com/jvhoof/fortinet-azure-solutions/tree/master/FortiGate.
Joeri

**Comment by hameedjafar** [comment]
Thanks a lot for your response, Joeri..
I was trying the below template.

https://github.com/fortinet/azure-templates/tree/master/FortiGate/FortiGate-AP-HA

I have 4 subnets and few other VNETs for Devops behind. I dont have a direct subnet attached 
(5th Protected Subnet). 

Is the above link can still be used or the new one , you sent..

https://github.com/jvhoof/fortinet-azure-solutions/tree/master/FortiGate/Active-Passive-SDN

Thanks
Hameed

**Comment by hameedjafar** [comment]
I am trying the below template with Standard_DS3_v2

https://github.com/jvhoof/fortinet-azure-solutions/tree/master/FortiGate/Active-Passive-SDN


{"telemetryId":"97b89178-b4d3-4125-a679-1e23cab4e1ef","bladeInstanceId":"Blade_c590430111a1462991d9d8da62601799_0_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"MultipleErrorsOccurred","message":"Multiple error occurred: BadRequest,BadRequest. Please see details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod-FGT-A' failed validation with message: 'The requested size for resource '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod-FGT-A' is currently not available in location 'northcentralus' zones '' for subscription 'efbc14f0-5afe-4e56-92db-6b2fe58a43a4'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."},{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod-FGT-B' failed validation with message: 'The requested size for resource '/subscriptions/efbc14f0-5afe-4e56-92db-6b2fe58a43a4/resourceGroups/RGRP_AZ_LCL_USNC_CORE/providers/Microsoft.Compute/virtualMachines/fw_az_lcl_usnc_prod-FGT-B' is currently not available in location 'northcentralus' zones '' for subscription 'efbc14f0-5afe-4e56-92db-6b2fe58a43a4'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'."}]}

**Comment by jvhoof** [comment]
Closing older issue. Compute resource not available in specified region.

**Comment by jvhoof** [comment]
Closing older issue. Compute resource not available in requested region.
