### ISSUE TITLE
Can we add availavility set option?

### ISSUE THREAD

**Issue by kichitan** [fortinet/azure-templates#21]
Hi

I notice the option to add a VM to an availability set is gone. Can we add it back?

I have a single VM that currently belongs to an availability set and I'd like to add a second VM to the same availability set but the template does not have an option for it.

**Comment by jvhoof** [comment]
Hi @kichitan,

Thank you for contact Fortinet. That is a good idea to a next version of the template. We have not enabled the Availability Set on the Single VM as this will remove failure notificatio from Microsoft if this single VM goes down as they expect at least a second VM to be in the AS. 

You can add a second VM to the AS using Azure CLI or Powershell.
https://www.petri.com/understanding-azure-availability-sets

Regards,

Joeri

**Comment by jvhoof** [comment]
Hi,

The latest version of the Single VM deployment has the Availability Set and Availability Zone options available in the template. You can select an existing AS or let the template create a new AS for you.

Hope this resolves your questions.

Regards,

Joeri
