### ISSUE TITLE
invalid license - please allow evaluation license

### ISSUE THREAD

**Issue by l4m3us3r** [fortinet/azure-templates#22]
I've spent the past couple days [unsuccessfully] trying to get an FGT VM working in azure for evaluation.

Can I request there be an evaluation license option for these azure templates?  as the eval license only allows 1cpu and 1gb ram and no https, it would have to be used with a B1s VM and set the external interface to allow http.

currently I can "deploy to azure", and then change the vm size to B1s, and the appliance boots but console says invalid license as 'Vcpu exceed 0'.

It would make things so much easier for those working with an Azure visual studio subscription or trial azure subscription... those subscriptions don't allow the azure credit to be used on non-ms services from the marketplace.  Making these templates eval license compatible would also be a great resource for those studying for NSE exams.

**Comment by jvhoof** [comment]
Hi,

Either you use PAYG license which means you will incur a cost from the Azure Marketplace for usage. Or you can send an email to azure@fortinet.com and request a trial license for the BYOL licensing model. 

Hope this will help you in your training for NSE certification. 

Regards,

Joeri

**Comment by l4m3us3r** [comment]
Awesome! I will try that.


Jeremy Finney | Senior Systems Engineer
E: ***@***.***<mailto:%7BE-mail%7D> P: 04 2600 600
W: concepts.co.nz<http://concepts.co.nz/> A: Level 4, 15 Willeston Street, Central, Wellington, New Zealand, 6011

**Comment by jvhoof** [comment]
Closing the issue for now. Feel free to reopen or create a new one in case you need more information.
