### ISSUE TITLE
static route to 172.16.136.65?

### ISSUE THREAD

**Issue by l4m3us3r** [fortinet/azure-templates#23]
currently the fortigate single VM template creates a static route to 172.16.136.65 (which doesn't appear to exist in this scenario).  Am I missing something or does a 172.16.136.65 interface exist somewhere?

current relevant config from the deployed VM:
config system interface
    edit "port1"
        set vdom "root"
        set ip 172.16.136.4 255.255.255.192
        set allowaccess ping http ssh
        set type physical
        set description "external"
        set snmp-index 1
    next
    edit "port2"
        set vdom "root"
        set ip 172.16.136.68 255.255.255.192
        set allowaccess ping http ssh
        set type physical
        set description "internal"
        set snmp-index 2
    next
end
config router static
    edit 1
        set gateway 172.16.136.1
        set device "port1"
    next
    edit 2
        set dst 172.16.136.0 255.255.252.0
        set gateway 172.16.136.65
        set device "port2"
    next
end

**Comment by jvhoof** [comment]
Hi,

The first IP in an Azure subnet is the default gateway for this subnet. Microsoft reserves the first 3 IPs for their usage. This is documented in the Microsoft docs. Look for VNET faq. You can also have a look at this video: https://youtu.be/tXLScLO-DRI

Regards,

Joeri

**Comment by jvhoof** [comment]
Closing the issue for now. Feel free to reopen or create a new one in case you need more information.
