### ISSUE TITLE
Typo/Bad name for Backend Pool when using Active-Passive-ELB-ILB template 

### ISSUE THREAD

**Issue by sebbbastien** [fortinet/azure-templates#26]
Hi,

When using the template "Active-Passive-ELB-ILB" Backend Pool is named ILB instead of ELB.

![image](https://user-images.githubusercontent.com/5331611/133777888-7133c713-899f-43cc-b378-f5abe6cb45c7.png)

Best regards,

**Comment by jvhoof** [comment]
Hi,

Thank you for contacting Fortinet. We have updated the templates in our development repo. We will post these changes to the github.com/fortinet repo.

Kind regards,

Joeri

**Comment by jvhoof** [comment]
Hi,

This has been fix in the repo for Active-Passive-ELB-ILB. 

Thanks for reporting.

Regards,

Joeri
