### ISSUE TITLE
Configuration Syn Fails After Rebooting Secondary VM in A/A Deployment

### ISSUE THREAD

**Issue by shareef009** [fortinet/azure-templates#27]
We have deployed A/A FortiGate's on Azure and configuration synchronization works fine until the Secondary VM is rebooted. To fix it, we have to disable the auto-scale and re-enable on the Secondary.

This is really affecting our production and we would like to request Fortinet to provide us with a fix or at-least acknowledge the issue and work on the fix.

**Comment by jvhoof** [comment]
Hi,

Thank you for reaching out. For this issue it is best to open a support ticket. Our staff will work with you to identify the issue and work with you towards a resolution.

https://www.fortinet.com/support/contact

Kind regards,

Joeri
