### ISSUE TITLE
AzureApplicationGateway

### ISSUE THREAD

**Issue by oluoyeneye** [fortinet/azure-templates#28]
Hi 

I am trying to deploy Scenario 1, but I am getting the below error. Any help to resolve this would be greatly appreciated. 

"There was an error downloading the template from URI 'https://raw.githubusercontent.com/40net-cloud/fortinet-azure-solutions/main/FortiGate/Active-Passive-APPGW/scenario1/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below."

https://github.com/jvhoof/fortinet-azure-solutions/tree/main/FortiGate/AzureApplicationGateway

**Comment by jvhoof** [comment]
Hi,

Thank you for contacting Fortinet. The repository link you used is only for development purposes. Can you try again with the below.

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AzureApplicationGateway

Kind regards,

Joeri
