### ISSUE TITLE
Link to Autoscale documentation for FortiGate 7.0 does not exist

### ISSUE THREAD

**Issue by jobbio** [fortinet/azure-templates#31]
The link on https://github.com/fortinet/azure-templates/tree/main/FortiGate to https://docs.fortinet.com/vm/azure/fortigate/7.0/azure-administration-guide/7.0.0/161167/deploying-auto-scaling-on-azure does not take you to a page for deploying auto scaling on 7.0. I can find auto-scaling information on the 6.4 documentation, but not 7.0.

**Comment by jvhoof** [comment]
Hi,

Verified the link and there is documentation for autoscaling on both 7.0 and 6.4 releases. Both links are working and the 7.0 link is provided correctly on the Github page you referred to. 

7.0: https://docs.fortinet.com/document/fortigate-public-cloud/7.0.0/azure-administration-guide/161167/deploying-auto-scaling-on-azure

6.4: https://docs.fortinet.com/document/fortigate-public-cloud/6.4.0/azure-administration-guide/161167/deploying-autoscaling-on-azure

Regards,

Joeri
