### ISSUE TITLE
Update FortiGate/AvailabilityZones/Active-Passive-ELB-ILB-AZ/ to support new instance types and fortios versions

### ISSUE THREAD

**Issue by dataolle** [fortinet/azure-templates#32]
It would be much appreciated if you could update  FortiGate/AvailabilityZones/Active-Passive-ELB-ILB-AZ/ to be in line with /FortiGate/Active-Passive-ELB-ILB

i.e. add support for FortiOS versions:
6.4.6,
6.4.7,
7.0.0,
7.0.1.

And the following instance types:
Standard_F1s
Standard_F2s
Standard_F1
Standard_F2
Standard_F2s_v2
Standard_F4s_v2
Standard_DS1_v2
Standard_DS2_v2
Standard_D2s_v3
Standard_D4s_v3

**Comment by skaas-cloudsec** [comment]
Hi Joeri,

The hyperlinks tagged in Fortigate configuration section is not working. 

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AvailabilityZones

![image](https://user-images.githubusercontent.com/64296447/145935368-df113cee-3125-4351-a79c-18a23134e690.png)

**Comment by jvhoof** [comment]
Hi,

The links have been updated now. 

Joeri

**Comment by jvhoof** [comment]
The latest versions of FGT have been added in this repo. Closing this issue.
