### ISSUE TITLE
Schema invalid URI

### ISSUE THREAD

**Issue by wraythezw** [fortinet/azure-templates#33]
https://github.com/fortinet/azure-templates/blob/main/FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ/azuredeploy.json

line 263, contains
"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deplymentTemplate.json#"

which should be

"$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"

**Comment by jvhoof** [comment]
Hi,

Thanks for the feedback. We have corrected this in our development repo and will publish this soon on github.com/fortinet. We are consolidating the AZ and AS templates so you can select the availability option during deployment.

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AvailabilityZones/Active-Active-ELB-ILB-AZ
https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/Active-Active-ELB-ILB

Regards,

Joeri

**Comment by wraythezw** [comment]
Thanks for the update Joeri!
