### ISSUE TITLE
FortiGate BYOL format

### ISSUE THREAD

**Issue by StefanIvemo** [fortinet/azure-templates#37]
I've tried to find out which format to pass the license to the template when using BYOL. So far I've been unsuccessful and have had to manually upload the `.lic` file after the initial deployment. I've been deploying the following offering: https://github.com/fortinet/azure-templates/tree/main/FortiGate/Active-Passive-ELB-ILB

Tried the following things:
- Deployed the template manually providing the license as a string input to the parameter file.
- Deployed FortiGate Active/Passive offering using the Azure Portal and Marketplace and uploading the license file in the portal wizard.

None of the above works. I have to manually add the license to the FortiGate nodes at first sign-in. Do I need to convert the license to any specific format?

**Comment by jvhoof** [comment]
Hi Stefan,

Thank you for opening this issue. The license file you download from support.fortinet.com can be uploaded when you deploy from the Azure Marketplace and in Advanced you upload the file. Also from the Github template if you select Azure Portal Wizard you will receive a very similar experience and you can upload the file. 

If you use the template without the createUiDefinition.json you can only enter a string value. In that case, you need to format the lic file into a string. Mainly the newline is an issue. In linux you could use a command like the one below to convert the lic to one large string.

awk 'sub("$", "\n\\n")' yourlicense.lic | tr -d '\n'

To troubleshoot your issue would would need to have an error you receive during deployment and the cloudinit debug you can output from the FortiGate CLI using the following command: diagnose debug cloudinit show

If you can post it here that would help to review this, please sanitize the output from any information you don't want to disclose.

Regards,

Joeri

**Comment by jvhoof** [comment]
All info provided online and via a meeting. Do not hesitate to contact us in case of additional questions.

Joeri
