### ISSUE TITLE
Issue in Active/Active tpl file for configuration 

### ISSUE THREAD

**Issue by simplyvishal** [fortinet/azure-templates#4]
Hi  Trying to execute code with few customization but not able to set all variables given in tpl file .

[fortigate.zip](https://github.com/fortinet/azure-templates/files/5375050/fortigate.zip)

**Comment by jvhoof** [comment]
Hi,

Thanks you for contacting Fortinet. Can you provide more specific description what you are trying to achieve? What is in the zip file? 

The terraform deployment you would need look at are located here: 
https://github.com/fortinet/azure-templates/tree/master/FortiGate/Terraform

Regards,

**Comment by jvhoof** [comment]
As we have not received further clarification I will close this issue. Feel free to open a new issue when more inforamation is needed or can be provided.

Joeri
