### ISSUE TITLE
Secure Fortigate (Active / Passive HA ELB ) Management external.

### ISSUE THREAD

**Issue by desmphil** [fortinet/azure-templates#40]
HI,

Ive deployed the active / passive template with 4NIC on each VM and ELB and ILB.

I want to secure the remote management PORT (NIC4) externally, using the NSG. 
In the template deployment there is only 1 NSG (externally) assigned to all the NIC

I believe there should be a second NSG for the Management Ports in the templates?

![image](https://user-images.githubusercontent.com/48382849/161309847-f1968d60-2dc0-4af1-8245-544803f9e67e.png)

**Comment by jvhoof** [comment]
Hi,

The templates provide a starting point. On the FortiGate, it it possible to apply access control and limit access.

If you want additional control it is always possible to update the general NSG which allows all traffic and is required by Azure or to create a new NSG that is specific for the HA Management network. 

Regards,

Joeri
