### ISSUE TITLE
Internet out from the Fortigate

### ISSUE THREAD

**Issue by sammons-rjohn** [fortinet/azure-templates#41]
I deployed this from the active/active design and all I have done is license and sign in and have no access from he CLI to ping 8.8.8.8. Am I missing something else I need to configure on the external Load Balancer?

Thanks

**Comment by jvhoof** [comment]
Hi,

Can you try using ‘exec telnet’ to a website on port 80? In Azure, ping is not the best test. 

Regards,

Joeri
