### ISSUE TITLE
Route to 168.63.129.16

### ISSUE THREAD

**Issue by dcb612** [fortinet/azure-templates#42]
The fortigates has routes to 168.63.129.16 pre configured. What is this ip use for?

**Comment by jvhoof** [comment]
Hi,

Thanks for contacting us. The IP 168.63.129.16 is a VIP used by the Microsoft Azure fabric for different network functions as you can read in the documentation below. We have this routing in the FortiGate to allow the Azure Load Balancer both on the external and internal side to be reachable by the VIP for the health probes on port 8008.

https://docs.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16

Hope this give you an anwer to your questions.

Regards,

Joeri
