### ISSUE TITLE
Can't Deploy the Active Passive SDN

### ISSUE THREAD

**Issue by desmphil** [fortinet/azure-templates#43]
ComputeResourceZoneConstraintDoesNotMatchPublicIPAddressZoneConstraint

-FGT-A has a zone constraint 1 but the PublicIPAddress FGTAPClusterPublicIP used by the compute resource via NetworkInterface or LoadBalancer has a different zone constraint Regional.",

**Comment by desmphil** [comment]
I also get theses messages 
{
    "status": "Failed",
    "error": {
        "code": "StandardSkuPublicIPAddressesMustBeStatic",
        "message": "Standard sku publicIp  FGTBMgmtPublicIP must have AllocationMethod set to Static.",
        "details": []
    }
}

**Comment by jvhoof** [comment]
Hi,

For Availability Zones all public IPs will need to be standard SKU. I think these errors are related to this. 

Regards,

Joeri
