### ISSUE TITLE
Closed connections to secondary window

### ISSUE THREAD

**Issue by LunaviSteve** [fortinet/azure-templates#44]
I have been using the FortiGate/Active-Active-ELB-ILB ARM template to deploy firewall pairs into Azure. I have noticed that once deployed with the auto-scale Configuration synchronization applied, the window for the secondary firewall doesn't stay open for vary long.
The Idle Timeout will be set for 15 minutes, but sometimes within 30 seconds, the connection will close without warning or explanation. The Primary will stay open for as long as the Idle Timeout is set for.

**Comment by jvhoof** [comment]
Hi,

Thank you using the ARM templates for FortiGate. For this issue it is best to open a support case with Fortinet as this is pertains to FortiOS itself. You can find concert details here: 

https://www.fortinet.com/support/contact

Regards,

Joeri
