### ISSUE TITLE
No internet access for non Microsoft IP's

### ISSUE THREAD

**Issue by evopilottuner** [fortinet/azure-templates#45]
I have an issue that my VM's in any of the default spokes with default configuration can not reach the internet. 

Checking the firewall logs i can see SENT traffic but 0 bytes received on the same session.

To add also that any traffic HTTPS/HTTP/NTP etc that is going over the same policy but to azure or Microsoft IP's has traffic flowing both sent and received in the same session.

My routes are good but i feel like i missed something during deployment

**Comment by evopilottuner** [comment]
![image](https://user-images.githubusercontent.com/37709852/171013258-f0b8e148-fa96-48b0-8887-8a680facca2d.png)

**Comment by evopilottuner** [comment]
Apologies, to also add: 
Both FortiGates can contact FortiGaurd and pull updates
I can connect from WAN to LAN via RDP to my test server deployed in spoke1 using a VIP on the WAN interface

**Comment by jvhoof** [comment]
Hi,

Appologies for the delay. Have you in the meantime resolved the issue? What template did you deploy? Did the public IP deploy correct and attached to the VM or Load Balancer?

Regards,

Joeri

**Comment by jvhoof** [comment]
Closing due to non activity. Please reopen or open a new issue if you have continues issues.

Joeri
