### ISSUE TITLE
Active-Passive SDN API Version Validation Failure

### ISSUE THREAD

**Issue by bruss22** [fortinet/azure-templates#46]
Trying to deploy A_P SDN and getting the following validation error. Azure support advising this is using the wrong API version. 

Should this be updated to "apiVersion": "2021-08-01" from "apiVersion": "2020-04-01",

“ Template validation failed while deploying the Fortigate VMs with the following error. {'code':'InvalidTemplate','message':'Deployment template validation failed: 'The template output reference to 'Microsoft.Network/publicIPAddresses/FW_Pub_IP' requires an API version. Please see https://aka.ms/arm-template for usage details.'.

**Comment by jvhoof** [comment]
Hi,

Thank you for the notification. We have updated the templates with a more recent api version. This should solve your deployment issue.

Regards,

Joeri
