### ISSUE TITLE
Active-Passive-SDN template fails with errors

### ISSUE THREAD

**Issue by prabhanjanhb** [fortinet/azure-templates#47]
Deployment fails with following error . Tried both Azure & Custom templates in Github & Marketplace , no good .  Azure support couldn't assist further as they advised the template owner must fix the issues with the template.  Tried multiple options by allowing template to create Public ip-address & by creating custom Public-IP Address .  Azure support informed about similar issue with another customer in June that was due to obsolete template.  Our Fortinet deployment for Accenture projects cannot continue until this problem is fixed .
Have discussed this issue with Ben Russell from Fortinet .  Please fix these issues on priority .
{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The template output reference to 'Microsoft.Network/publicIPAddresses/testfortinet' requires an API version. Please see [https://aka.ms/arm-template for usage details.'."
}

**Comment by jvhoof** [comment]
Hi,

Thank you for reaching out. We have been in contact via Ben. The templates on this repo have been updated with more recent API versions. This should solve your deployment problem. If you have any additional issues you can update the issue or reach out to Ben.

Regards,

Joeri
