### ISSUE TITLE
Each VM is being deployed in AZ 2

### ISSUE THREAD

**Issue by Eggs1224** [fortinet/azure-templates#5]
Hello,

Deployed the template and both VMs show to be in AZ 2, template says A will be deployed in AZ 1 and B will be deployed in AZ 2,

Am I missing something?

Thanks,
Neil

**Comment by jvhoof** [comment]
Hi Neil,

That is indeed a typo in the template from some copy/paste action. This is being fixed in the next release of templates.

You can adapt the zones in the template by looking for this section and change it to your requirements. 
"zones": [
        "2"
      ],

Regards,

Joeri

**Comment by jvhoof** [comment]
Hi Neil,

The templates have been updated now. The FortiGate-VMs deploy in zone 1 and 2 respectively.

Joeri
