### ISSUE TITLE
Load Balancer doesn't use Zone Redundancy when you set the machines to Zone Redundancy 

### ISSUE THREAD

**Issue by RAWRitsCloud** [fortinet/azure-templates#50]
Hey, 

When you deploy any of the templates that support putting the Virtual Machines in Availability zones, the standard load balancer that is deployed with it is deployed into "No Zone" which kind of makes the whole purpose of Zonal redundancy pointless.

Could you add the Zones into the front-end configuration of the load balancers the same way you do for the Virtual machines.

**Comment by jvhoof** [comment]
Hi,

Thank you for opening this issue. After reviewing this it seems that Microsoft has changed the behavior of their API. Before 2020-08-01 the default behavior was to create a zone redundant PIP. This is no longer the case. 
https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/create-public-ip-template

We have update the main templates in our test repo on the link below. These will now create zone redundant PIPs for the front-end configuration.

https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate

Let us know if this is indeed what you are referring to and we can push this change to our main repo.

Regards,

Joeri

**Comment by RAWRitsCloud** [comment]
Hi Joeri

Yes that seems to work now! 

Thank you
James

**Comment by jvhoof** [comment]
Hi James,

Perfect. The templates on this repo are now also up to date.

Thank you for reporting this issue. Happy holidays,

Joeri
