### ISSUE TITLE
Fortiweb HA A/P behind Azure load balancer.

### ISSUE THREAD

**Issue by adriatikb** [fortinet/azure-templates#52]
Hi,

Knowing that AzureLoad balancer is in only as A/A mode how we would manage A/P on Fortiweb ?
is there any way to force this to LB?

regards
Adi

**Comment by jvhoof** [comment]
Hi @adriatikb,

Apologies for delay in the response. Below a setup for A/P using FortiWeb.

https://docs.fortinet.com/document/fortiweb-public-cloud/latest/use-case-high-availability-for-fortiweb-on-azure/906679/connecting-to-fortiwebs-gui-and-cli
https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiWeb/Active-Passive

Regards,

Joeri
