### ISSUE TITLE
Sessions and Config Sync for FGT Active-Active-ELB-ILB

### ISSUE THREAD

**Issue by Maher023** [fortinet/azure-templates#54]
Hello,
I have configured session and configuration synchronization as mentioned in the last section in article below, but my changes in the Primary (creation Policy or other) are not synchronized in the secondary, do you know please this is the raison? is there anything else to configure?
for information:
I configured session synchronization in Port1, and config synchronization in port2.
another question: what are the troubchoot commands to check if my synchro config is well configured?

https://github.com/fortinet/azure-templates/tree/main/FortiGate/Active-Active-ELB-ILB

**Comment by mobilesuitzero** [comment]
Hi,

You can try to check if the checksum are the same on both autoscale members.

https://docs.fortinet.com/document/fortigate/7.2.4/administration-guide/681076/querying-autoscale-clusters-for-fortigate-vm

Cheers
