### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by paulkelly100** [fortinet/azure-templates#59]
I have an issue deploying a FortiGate NVA in Azure.
I attepmted to deploy the NVA for Azure Virtual WAN Secured by Fortinet FortiGate.
The deployement went through ok, but the managed application now shows the following message:
"The application failed to provision. Contact application support for more information"

If I try and delete the managed application to then attempt to redeploy I get the following message: 

Failed to delete managed application
Failed to delete managed application 'fgngfw01'. Error: Deletion of resource group 
'mrg-fortigate_vwan_nva-XXXXXXXXXXXX' failed as resources with identifiers 
'Microsoft.Network/networkVirtualAppliances/fgngfw-XXXXXXX-XXXXXXX' could not be deleted. 
The provisioning state of the resource group will be rolled back. The tracking Id is 
'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'. Please check audit logs for more details.

Any one come across this before or know how to resolve.

I contact Fortinet TAC and they said they don't support deployments.
I also have an open case with Microsoft in case it is platform related.

**Comment by paulkelly100** [comment]
Microsoft has advised "We are not able to load the resource anymore and after checking the log it seems stuck on the backend. Please allow us some time for the further investigation and check if we need to engage product team helping on the issue."

**Comment by jvhoof** [comment]
Thank you for reaching out. Deleting, creation of the FortiGate inside VWAN is indeed up to Microsoft to control and assist. If you continue to have issues with your deployment you can ready out to azure@fortinet.com.

Regards,

Joeri
