### ISSUE TITLE
Active/Passive High Available FortiGate pair with Fabric Connector Failover - Template failure ( Azure Markeplace)

### ISSUE THREAD

**Issue by albertphancellenza** [fortinet/azure-templates#61]
Hello,

I am trying to create a new Fortigate from Azure Marketplace with Active/Passive High Available FortiGate pair with Fabric Connector Failover  configuration.

When using three existing Standard public IPs , Public IP Verification is all good, however on the review screen the following error is occuring :

{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template output reference to 'Microsoft.Network/publicIPAddresses/pip-fg-cluster-dsi-prd' requires an API version. Please see https://aka.ms/arm-syntax for usage details.'."}

Seems to be related to same context to the  closed issue (https://github.com/fortinet/azure-templates/issues/46)

Kind regards,

**Comment by jvhoof** [comment]
Hi Albert,

Appologies for the delay in the response. Can you check an updated on the following link https:/github.com/40net-cloud/fortinet-azure-solutions/FortiGate? If that works we will update this repo as well.

Regards,

Joeri

**Comment by albertphancellenza** [comment]
It should work fine. Thanks for the bugfix. 

Kind regards,
